### ISSUE TITLE
!data.exists()

### ISSUE THREAD

**Issue by dreadjr** [pkaminski/fireplan#1]
How do you suggest doing !data.exists()

I tried NOT and not yaml operator.

Could do my own functions, but i am probably just missing something.

**Comment by pkaminski** [comment]
You're probably just running into the weird YAML syntax where a leading `!` has special significance.  I get around by putting the expression in parenthesis:  `(!data.exists())`.

**Comment by dreadjr** [comment]
yes, thank you!
