### ISSUE TITLE
.indexOn: .value

### ISSUE THREAD

**Issue by pgherveou** [pkaminski/fireplan#4]
Hey @pkaminski 
I dont think its possible right now when using fireplan
https://www.firebase.com/docs/security/guide/indexing-data.html#section-indexing-order-by-value

**Comment by pgherveou** [comment]
My bad just had to add the indexed key word for this one
wondering if the other index type are supported as well
https://www.firebase.com/docs/security/guide/indexing-data.html

**Comment by pkaminski** [comment]
Yes, the `indexed` keyword should automatically resolve to the correct type
of index.  Please let me know if you find that it doesn't...

On Wed, Jul 15, 2015 at 2:08 PM, PG Herveou notifications@github.com
wrote:

> My bad just had to add the indexed key word
> wondering if the other index type are supported as well
> https://www.firebase.com/docs/security/guide/indexing-data.html
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pkaminski/fireplan/issues/4#issuecomment-121748015.

## 

  Piotr Kaminski piotr@ideanest.com
  "That bun is dirty.  Don't eat that bun."
