### ISSUE TITLE
boolean expression

### ISSUE THREAD

**Issue by pgherveou** [pkaminski/fireplan#6]
Hey there, this is not really an issue but just a quick question

I just wrote this expression in my yaml
`.write: isAdmin || (deleteOnly && $userId === auth.uid)`
and got this in my json
`".write": "auth.role === 'admin' || data.exists() && !newData.exists() && $userId === auth.uid"`

Are you getting rid of the parentheses because you know its safe too, or is this not intended

**Comment by pkaminski** [comment]
I parse the expression using http://esprima.org/ and, after transformation, re-emit the code using https://github.com/estools/escodegen, so I'm not surprised that some lexical details get changed.  If I had to guess, it's likely that escodegen understands operator precedence and automatically outputs a minimal representation of the abstract syntax tree.

**Comment by pgherveou** [comment]
Ok thks for the precision @pkaminski
