### ISSUE TITLE
deep paths index

### ISSUE THREAD

**Issue by pgherveou** [pkaminski/fireplan#7]
hey @pkaminski is it possible to add a deep path index  (see 
https://www.firebase.com/blog/2015-09-24-atomic-writes-and-more.html Ordering queries by deep paths)
with fireplan?

**Comment by pkaminski** [comment]
Yeah, I was just thinking about that. It's not currently supported, but I
think could be added with a syntax like `indexed(ancestorKey)`. I might
give it a try later this week but if you want to give it a try I'll be
happy to accept a PR.

**Comment by pkaminski** [comment]
Actually, I just realized it's even easier than that and fixed it.  Just use `indexed` as usual, and the index declaration will automatically be lifted up to the nearest wildcard ancestor.  (If you need something fancier, like indexing across multiple layers of wildcards, then that will need somewhat more work.)

**Comment by pgherveou** [comment]
Pretty cool i ll give it a try, thks for yor help!
